CREATE TABLE INCOME (
    INCOME_ID NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    SOURCE VARCHAR2(50) DEFAULT 'PRIMARY' NOT NULL,
    AMOUNT_IN NUMBER(10,2) NOT NULL,
    IN_DATE DATE DEFAULT SYSDATE,
    EXPENSE VARCHAR2(50) NOT NULL,
    AMOUNT_OUT NUMBER(10,2) NOT NULL CHECK (AMOUNT_OUT >= 100.00 AND AMOUNT_OUT <= 50000.00),
    OUT_DATE DATE
);


INSERT INTO INCOME VALUES(123, 'RAM', 'PRIMARY', 50000.00, TO_DATE('10-10-24', 'DD-MM-YY'), 'GROCERY', 12500.00, TO_DATE('12-10-24', 'DD-MM-YY'));
SELECT * FROM INCOME;

UPDATE INCOME SET EXPENSE = 'TOUR' WHERE INCOME_ID = 123;
SELECT * FROM INCOME;

DROP TABLE INCOME;